DCE.Hertz2/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DCE.Hertz2.Models
{
    public class Invoice
    {
        public int InvoiceId { get; set; }
        public int? CustomerId { get; set; }
        [Display(Name="Invoice Number")]
        public string InvoiceNumber { get; set; }
        public string Account { get; set; }
        public string ChargeTo { get; set; }
        public string Address2 { get; set; }
        
        [DisplayFormat(DataFormatString="{0:d-MMM-yy}")]
        [Display(Name="Invoice Date")]
        public DateTime? InvoiceDate { get; set; }
        public string GSTNumber { get; set; }
        public decimal? GSTAmount { get; set; }
        public string Reference { get; set; }
        public string Reservation { get; set; }
        public string OrderNumber { get; set; }
        public string VoucherNumber { get; set; }
        public string FreqFlyer { get; set; }
        public string PayType { get; set; }
        public string RateCDP { get; set; }
        public string Hirer { get; set; }
        public string PickUpLocation { get; set; }

        [DisplayFormat(DataFormatString = "{0:d-MMM-yy}")]
        public DateTime? PickUpDateTime { get; set; }
        public string ReturnLocation { get; set; }
        [DisplayFormat(DataFormatString = "{0:d-MMM-yy}")]
        public DateTime? ReturnDateTime { get; set; }
        public string LicenceNo { get; set; }
        public string VehicleCharged { get; set; }
        public string ReturnVehicle { get; set; }
        public int? KMOut { get; set; }
        public int? KMIn { get; set; }
        public int? CarbonEmissions { get; set; }
        public string Currency { get; set; }
        [DisplayFormat(NullDisplayText = "0.00")]
        public decimal? TotalChargesPaid { get; set; }


        public int?  KMDriven
        {
            get
            {
                if (KMIn.HasValue && KMOut.HasValue)
                {
                    return KMIn.Value - KMOut.Value;
                }
                return 0;
            }
            
        }

        public Customer Customer { get; set; }
        public virtual ICollection<Charges> Charges { get; set; }

    }
}

DCE.Hertz2/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DCE.Hertz2.DB;
using DCE.Hertz2.Models;
using DCE.Hertz2.ViewModel;

namespace DCE.Hertz2.Controllers
{
    [Authorize(Roles="Admin")]
    public class CustomerController : Controller
    {
        private HertzInvoiceDB db = new HertzInvoiceDB();
        private UsersContext userDb = new UsersContext();

       

       
        
        #region Auto generated    
        public ActionResult Index()
        {
            //var customers = db.Customers.Join(db.UserProfiles, c => c.Id, u => u.CustomerId,
            //    (c, u) => new Customer
            //    {
            //        Id = c.Id,
            //        Account = c.Account,
            //        Name = c.Name,
            //        Company = c.Company,
            //        PayType = c.PayType,
            //        City = c.City,
            //        UsersCount = c.UserProfiles.Count()
            //    });
            //return View(customers.ToList());
            var customers = db.Customers.Include(c=>c.UserProfiles).Include(c=>c.Invoices);
            foreach (var customer in customers)
            {
                customer.UsersCount = customer.UserProfiles.Count();
            }
            return View(customers);
        }
            
      
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer.ToDetailViewModel());
        }
       
        // GET: Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Account, Name, Company, PayType, City, Country")] CustomerListViewModel customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer.ToModel());
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer.ToViewModel());
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Account, Name, Company, PayType, City, Country")] CustomerListViewModel customer)
        {
            var entity = customer.ToModel();
            if (ModelState.IsValid)
            {
                db.Entry(entity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer.ToViewModel());
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
                userDb.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

DCE.Hertz2/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DCE.Hertz2.Models;
using DCE.Hertz2.DB;
using DCE.Hertz2.ViewModel;
using DCE.Hertz2.Filters;
using System.Configuration;
using PagedList;

namespace DCE.Hertz2.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private HertzInvoiceDB db = new HertzInvoiceDB();
        private UsersContext userDb = new UsersContext();

        public ActionResult Autocomplete(string term)
        {
            var model = db.Invoices.Where(i => i.InvoiceNumber.StartsWith(term))
                .Take(10)
                .Select(i => new
                {
                    label = i.InvoiceNumber
                });
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "User")]
        public ActionResult Index(string searchKey, string searchTerm, int page = 1)
        {
            string account = userDb.UserProfiles.Where(u => u.UserName == User.Identity.Name).Select(u => u.Account).FirstOrDefault();
            Customer customer = db.Customers.Where(c => c.Account == account).FirstOrDefault();
            var invoices = db.Invoices.Where(i => i.Customer.Account == account && (searchTerm == null || i.InvoiceNumber.StartsWith(searchTerm)))
                .OrderByDescending(i => i.InvoiceDate).ToPagedList(page, 10);

            var model = new ViewModel.InvoiceSearchViewModel { Customer = customer, Invoices = invoices };
            if (model == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_InvoiceSearchResult", invoices);
            }

            return View(model);

        }

        #region Auto generated
        //[Authorize(Roles="User")]
        //public ActionResult Index()
        //{
        //    string account = userDb.UserProfiles.Where(u=> u.UserName ==  User.Identity.Name).Select(u=>u.Account).FirstOrDefault();

        //    //return View(db.Invoices.ToList());
        //    return View(db.Invoices.Where(i => i.Account == account).ToList());
        //}
        public ActionResult List()
        {
            return View(db.Invoices.ToList().ToViewModel());
        }


        public ActionResult Details(int id = 0)
        {
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        public ActionResult Download(int id = 0)
        {
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            string InvoicePdfFilePath = ConfigurationManager.AppSettings["InvoicePdfFilePath"];
            string invoicePdfpath = string.Format(@"{0}\{1}.pdf", InvoicePdfFilePath, invoice.InvoiceNumber);
            return File(invoicePdfpath, "application/octet-stream", invoice.InvoiceNumber + ".pdf"); //application/pdf

        }
        public ActionResult View(int id = 0)
        {
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            string InvoicePdfFilePath = ConfigurationManager.AppSettings["InvoicePdfFilePath"];
            string invoicePdfpath = string.Format(@"{0}\{1}.pdf", InvoicePdfFilePath, invoice.InvoiceNumber);
            return File(invoicePdfpath, "application/pdf");

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(invoice);
        }

        public ActionResult Edit(int id = 0)
        {
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invoice);
        }


        public ActionResult Delete(int id = 0)
        {
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
                userDb.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

DCE.Hertz2/Views/Invoice/Default.cshtml
@model DCE.Hertz2.Models.Customer

@{
    ViewBag.Title = "Default";
    var invoice = Model.Invoices.FirstOrDefault();
}

<div class="container">
    <div class="jumbotron">
        <h2>@Html.DisplayFor(model => model.Name)</h2>
        <p> @Html.DisplayFor(model => model.Address2)</p>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h3>Invoices</h3>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => invoice.InvoiceNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => invoice.InvoiceDate)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => invoice.Hirer)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => invoice.PickUpLocation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => invoice.PickUpDateTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => invoice.ReturnLocation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => invoice.ReturnVehicle)
                    </th>


                </tr>

                @foreach (var item in Model.Invoices)
                {
                    <tr>
                        <td>@Html.HiddenFor(modelItem => item.CustomerId)
                            @Html.DisplayFor(modelItem => item.InvoiceNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InvoiceDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Hirer)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PickUpLocation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PickUpDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReturnLocation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReturnVehicle)
                        </td>


                        <td>
                            <div class="btn-group-vertical">
                                <a href="@Url.Action("Download", "Invoice", new { id = item.InvoiceId })" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-edit"></span></a>
                                <a href="@Url.Action("Details", "Invoice", new { id = item.InvoiceId })" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-th-list"></span></a>
                            </div>
                        </td>
                    </tr>
                }

            </table>

        </div>
        <div class="col-md-2">
            <div class="container-fluid">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Customer</h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Account)
                            </label>
                            <br />
                            <div>
                                @Html.DisplayFor(model => model.Account)
                            </div>
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Name)
                            </label>
                            <div>
                                @Html.DisplayFor(model => model.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Company)
                            </label>
                            @Html.DisplayFor(model => model.Company)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.PayType)
                            </label>
                            @Html.DisplayFor(model => model.PayType)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Status)
                            </label>
                            @Html.DisplayFor(model => model.Status)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Address1)
                            </label>
                            @Html.DisplayFor(model => model.Address1)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Address2)
                            </label>
                            @Html.DisplayFor(model => model.Address2)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.City)
                            </label>
                            @Html.DisplayFor(model => model.City)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.State)
                            </label>
                            @Html.DisplayFor(model => model.State)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Zip)
                            </label>
                            @Html.DisplayFor(model => model.Zip)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Country)
                            </label>
                            @Html.DisplayFor(model => model.Country)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Email)
                            </label>
                            @Html.DisplayFor(model => model.Email)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => model.Phone)
                            </label>
                            @Html.DisplayFor(model => model.Phone)
                        </div>
                    </div>
                </div>
            </div>
            <p>

                <a href="@Url.Action("Edit", "Customer", new { id = Model.Id })" class="btn btn-success btn-sm">link text <span class="glyphicon glyphicon-th-list"></span></a>
                @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </div>
</div>

DCE.Hertz2/Views/Invoice/Index.cshtml
@model  DCE.Hertz2.ViewModel.InvoiceSearchViewModel

@{
    ViewBag.Title = "Default";
    var customer = Model.Customer;
}

<div class="container">
    <div class="jumbotron">
        <h2>@Html.DisplayFor(c => customer.Account)</h2>
        <p>@Html.DisplayFor(c => customer.Address2)</p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Invoices</h3>
            <form method="get" action = "@Url.Action("Index")" data-zzz-ajax="true" data-zzz-target="#divInvoiceResult">

                <div class="row">
                    <div class="col-md-3">
                        <select class="form-control" name="searchKey">
                            <option value="InvoiceNumber">Invoice Number</option>
                            <option value="AggrementNumber">Agreement Number</option>
                            <option value="ReferenceNumber">Reference Number</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <input type="search" name="searchTerm" data-zzz-autocomplete="@Url.Action("Autocomplete")" class="form-control" />
                    </div>
                    <div class="col-md-3">
                        <input type="submit" value="Search" class="btn btn-default" />
                    </div>
                </div>
                <p>
                </p>
            </form>
            @Html.Partial("_InvoiceSearchResult", Model.Invoices)
            <p>
                @Html.ActionLink("Back to List", "Index", "Invoice", null, new { @class = "btn btn-default btn-md" })
            </p>
        </div>

    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="container-fluid">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Customer</h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Account)
                            </label>
                            <br />
                            <div>
                                @Html.DisplayFor(model => customer.Account)
                            </div>
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Name)
                            </label>
                            <div>
                                @Html.DisplayFor(model => customer.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Company)
                            </label>
                            @Html.DisplayFor(model => customer.Company)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.PayType)
                            </label>
                            @Html.DisplayFor(model => customer.PayType)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Status)
                            </label>
                            @Html.DisplayFor(model => customer.Status)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Address1)
                            </label>
                            @Html.DisplayFor(model => customer.Address1)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Address2)
                            </label>
                            @Html.DisplayFor(model => customer.Address2)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.City)
                            </label>
                            @Html.DisplayFor(model => customer.City)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.State)
                            </label>
                            @Html.DisplayFor(model => customer.State)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Zip)
                            </label>
                            @Html.DisplayFor(model => customer.Zip)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Country)
                            </label>
                            @Html.DisplayFor(model => customer.Country)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Email)
                            </label>
                            @Html.DisplayFor(model => customer.Email)
                        </div>

                        <div class="form-group">
                            <label>
                                @Html.DisplayNameFor(model => customer.Phone)
                            </label>
                            @Html.DisplayFor(model => customer.Phone)
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

@section Scripts {

}

DCE.Hertz2/Views/Invoice/_InvoiceSearchResult.cshtml
@model IPagedList <DCE.Hertz2.Models.Invoice>
@{
    
}
<div id="divInvoiceResult">
    <div class="pagedList" data-zzz-target="#divInvoiceResult">
        @Html.PagedListPager(Model, page =>Url.Action("Index", new { page}),
        PagedListRenderOptions.Classic)
    </div>

    <table class="table">
        <tr class="active">
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().InvoiceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().InvoiceDate)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Hirer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().PickUpLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().PickUpDateTime)
            </th>
            @* <th>
                        @Html.DisplayNameFor(model => model.ReturnLocation)
                    </th>*@
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ReturnVehicle)
            </th>
            <th></th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.HiddenFor(modelItem => item.CustomerId)
                    <a href="@Url.Action("Details", "Invoice", new { id = item.InvoiceId })" >@Html.DisplayFor(modelItem => item.InvoiceNumber)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InvoiceDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hirer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PickUpLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PickUpDateTime)
                </td>
                @* <td>
                            @Html.DisplayFor(modelItem => item.ReturnLocation)
                        </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnVehicle)
                </td>


                <td>
                    <div class="btn-group-vertical">
                        <a href="@Url.Action("View", "Invoice", new { id = item.InvoiceId })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-th-list"></span></a>
                        <a href="@Url.Action("Download", "Invoice", new { id = item.InvoiceId })" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-download"></span></a>

                    </div>
                </td>
            </tr>
        }

    </table>
</div>